title: En's Hub
# description: En Zhou's Hub in Midnight theme for GitHub Pages.
show_downloads: false
google_analytics: UA-105338850-1
theme: jekyll-theme-midnight


twitter_username: zhouennathan
github_username: zhouen
linkedin_username: zhouennathan
google_plus_username: +EnZhou
facebook_username: enzhou

permalink: /blog/:year/:month/:day/:title
